import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Download, Code, FileJson, Printer, Loader2 } from 'lucide-react';
import { saveAs } from 'file-saver';
import TurndownService from 'turndown';

export default function ExportMenu({ projectTitle, htmlContent }: { projectTitle: string, htmlContent: string }) {
  const [isExporting, setIsExporting] = useState(false);

  const safeTitle = projectTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase() || 'document';

  const getWysiwygHTML = () => {
    // We fetch the live rendered DOM from the editor to guarantee perfect WYSIWYG
    // and avoid the raw JSON format saved in Firebase.
    const editorEl = document.querySelector('.ProseMirror');
    if (editorEl) {
      return editorEl.innerHTML;
    }
    // Fallback if not found 
    return `<p>Failed to capture editor content.</p>`;
  };

  const wrapHTML = (content: string) => `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${projectTitle}</title>
      
      <!-- Load standard fonts matching the editor -->
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Merriweather:ital,wght@0,400;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
      
      <!-- Load Tailwind and configure it inline exactly like the canvas renderer -->
      <script src="https://cdn.tailwindcss.com?plugins=typography"></script>
      <script>
        tailwind.config = {
          theme: {
            extend: {
              fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                serif: ['Merriweather', 'serif'],
                mono: ['JetBrains Mono', 'monospace'],
              },
              typography: {
                DEFAULT: {
                  css: {
                    maxWidth: 'none',
                    color: '#111827', // text-gray-900
                    a: { color: '#3182ce', '&:hover': { color: '#2c5282' } },
                    code: { color: '#805ad5', backgroundColor: '#f3f4f6', padding: '0.2em 0.4em', borderRadius: '0.25rem', fontWeight: '400' },
                    'code::before': { content: '""' },
                    'code::after': { content: '""' },
                    pre: { backgroundColor: '#1f2937', color: '#f3f4f6', padding: '1rem', borderRadius: '0.5rem', overflowX: 'auto' },
                    'pre code': { backgroundColor: 'transparent', padding: '0', color: 'inherit', borderRadius: '0' },
                    table: {
                      width: '100%',
                      tableLayout: 'fixed',
                      borderCollapse: 'collapse',
                      marginTop: '2em',
                      marginBottom: '2em',
                    },
                    thead: { borderBottomWidth: '2px', borderBottomColor: '#e5e7eb' },
                    'thead th': { color: '#374151', fontWeight: '600', padding: '0.75rem', textAlign: 'left', backgroundColor: '#f9fafb' },
                    'tbody tr': { borderBottomWidth: '1px', borderBottomColor: '#e5e7eb' },
                    'tbody td': { padding: '0.75rem', alignVertical: 'top' },
                  }
                }
              }
            }
          }
        }
      </script>
      
      <style>
        /* Essential overrides for Tiptap structural classes that Tailwind Typography doesn't handle natively */
        
        /* Alignment classes generated by Tiptap */
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .text-justify { text-align: justify; }

        p.is-editor-empty:first-child::before { content: attr(data-placeholder); float: left; color: #adb5bd; pointer-events: none; height: 0; }
        
        img { display: block; height: auto; max-width: 100%; border-radius: 0.5rem; transition: all 0.2s ease-in-out; }
        img[data-align="left"] { float: left; margin: 0 1.5rem 1.5rem 0; }
        img[data-align="right"] { float: right; margin: 0 0 1.5rem 1.5rem; }
        img[data-align="center"] { margin: 1.5rem auto; display: block; }
        img[data-size="small"] { width: 25%; }
        img[data-size="medium"] { width: 50%; }
        img[data-size="large"] { width: 75%; }
        img[data-size="full"] { width: 100%; }

        blockquote { border-left: 4px solid #e5e7eb; margin-left: 0; padding-left: 1rem; font-style: italic; color: #4b5563; }
        .scene-break { text-align: center; letter-spacing: 0.5em; margin: 3rem 0; font-weight: bold; color: #9ca3af;}
        
        .callout { padding: 1rem; margin: 1.5rem 0; border-radius: 0.5rem; border-left: 4px solid #ccc; background: #f9f9f9; }
        .callout[data-type="info"] { background: #eff6ff; border-left-color: #3b82f6; }
        .callout[data-type="warning"] { background: #fffbeb; border-left-color: #f59e0b; }
        .callout[data-type="success"] { background: #f0fdf4; border-left-color: #22c55e; }
        .callout[data-type="error"] { background: #fef2f2; border-left-color: #ef4444; }
        
        table .selectedCell { background-color: rgba(200, 200, 255, 0.4); }

        @media print {
          @page { margin: 2cm; }
          body { 
            padding: 0; 
            -webkit-print-color-adjust: exact !important; 
            print-color-adjust: exact !important; 
          }
          .callout, pre, blockquote { break-inside: avoid; }
          table { break-inside: auto; }
          tr { break-inside: avoid; break-after: auto; }
          img { break-inside: avoid; max-width: 100% !important; }
        }
      </style>
    </head>
    <body class="prose prose-sm sm:prose-base lg:prose-lg font-serif text-gray-900 mx-auto max-w-[800px] p-8">
      ${content}
    </body>
    </html>
  `;

  const handleExportHTML = () => {
    const fullHtml = wrapHTML(getWysiwygHTML());
    const blob = new Blob([fullHtml], { type: 'text/html;charset=utf-8' });
    saveAs(blob, `${safeTitle}.html`);
  };

  const handleExportMarkdown = () => {
    const turndownService = new TurndownService({ headingStyle: 'atx' });
    const markdown = turndownService.turndown(getWysiwygHTML());
    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    saveAs(blob, `${safeTitle}.md`);
  };

  const handlePrint = () => {
    // We open a new window to bypass iframe modal restrictions cleanly.
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert("Popup blocker prevented printing. Please allow popups for this site.");
      return;
    }
    printWindow.document.write(wrapHTML(getWysiwygHTML()));
    printWindow.document.close();
    printWindow.focus();
    
    // Give Tailwind via CDN + typography plugin time to compile and apply styles,
    // plus images time to load before triggering native print
    setTimeout(() => {
      printWindow.print();
    }, 1500);
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger render={<Button variant="outline" size="sm" disabled={isExporting} className="rounded-full hidden sm:flex">
          {isExporting ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Download className="h-4 w-4 mr-2" />}
          {isExporting ? "Exporting..." : "Export"}
        </Button>} />
      <DropdownMenuContent align="end" className="w-48">
        <DropdownMenuItem onClick={handleExportHTML}>
          <Code className="mr-2 h-4 w-4 text-orange-500" />
          HTML Document
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleExportMarkdown}>
          <FileJson className="mr-2 h-4 w-4 text-purple-500" />
          Markdown (.md)
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handlePrint}>
          <Printer className="mr-2 h-4 w-4 text-gray-500" />
          Print / Save as PDF
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
